### ISSUE TITLE
Terraform Support

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#114]
Description: We want to support the ~1% of possible uses for Terraform that are used by the majority of companies using it.
Due: Milestone 2
Time Est: 20 hours
Actual Time:

Requires:
- [x] Determine what we will support
- [x] #98 
- [x] #97 
- [x] #91 
- [x] #90 
- [x] #89 
- [x] #87 
- [x] #86 
- [x] ~~#84~~ (Moved to Milestone 3)
AWS Resources:
- [x] #127 
- [ ] ~~#128~~  (Moved to Milestone 3)
- [x] #129
- [x] #130
- [x] #131
- [x] #132
- [x] #133
- [x] #134
- [x] ~~#135~~  (Moved to Milestone 3)
- [x] ~~#136~~  (Moved to Milestone 3)
- [x] #137
- [x] ~~#138~~
- [x] #139

**Comment by brennanwilkes** [comment]
AWS Resources:
- [ ] Lamda Functions
- [ ] S3
- [ ] Glacier
- [ ] Dynamo DB
- [ ] RDS
- [ ] Load Balencing
- [ ] AMI


Misc Tasks
- [ ] Deepen Ec2 support
- [ ] Networking configuration for ec2 and other resources

**Comment by keanelekenns** [comment]
I've added @skorsch  and @DerekRobin because there are a lot of front end components to this. We will have to chat about what to show the user

**Comment by brennanwilkes** [comment]
Please see [https://github.com/devxp-ca/devxp/blob/main/resources/example.md](https://github.com/devxp-ca/devxp/blob/main/resources/example.md) for a list of resources and their required formats.
@skorsch @DerekRobin

**Comment by DerekRobin** [comment]
Closing this because all items are either done or have been moved to M3
