### ISSUE TITLE
Polished UI & UX

### ISSUE THREAD

**Issue by keanelekenns** [devxp-ca/devxp#119]
Description: We would like a noticeable difference in the user interface and the user experience between milestone 2 and 3.

Due: Milestone 3
Time Est: Evolving continuously

Requires:
- [x] #237
- [x] #195
- [x] #58 
- [x] #62 
- [x] ~~#32~~ Moved to final submission
- [x] #196
- [x] #166
- [x] #194 (This is a major feature in and of itself)
- [x] ~~#215~~ Moved to final submission
